# Usa una imagen base de Node.js compatible con Vite (v20 o superior)
FROM node:20-alpine

# Establece el directorio de trabajo
WORKDIR /var/www/html

# Copia el código de tu aplicación al contenedor
COPY . .
